// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function LoadFileAsync(arg1) {
  return window['go']['main']['App']['LoadFileAsync'](arg1);
}
