// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {src} from '../models';

export function LoadFile(arg1:number):Promise<Array<src.Image>>;

export function LoadFileAsync(arg1:number):Promise<void>;

export function OpenImage(arg1:string):Promise<void>;

export function PingServer(arg1:string):Promise<boolean>;

export function SubmitImages(arg1:string):Promise<void>;

export function SubmitImagesV2(arg1:string):Promise<void>;
