// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function LoadFileAsync(arg1) {
  return window['go']['main']['App']['LoadFileAsync'](arg1);
}

export function OpenImage(arg1) {
  return window['go']['main']['App']['OpenImage'](arg1);
}

export function PingServer(arg1) {
  return window['go']['main']['App']['PingServer'](arg1);
}

export function SubmitImages(arg1) {
  return window['go']['main']['App']['SubmitImages'](arg1);
}

export function SubmitImagesV2(arg1) {
  return window['go']['main']['App']['SubmitImagesV2'](arg1);
}
